### ISSUE TITLE
Removal of paxtools-jena-io breaks psimi

### ISSUE THREAD

**Issue by MaybeJustJames** [BioPAX/Paxtools#49]
Hi,
I'm trying to update [MICommunity/psimi](https://github.com/MICommunity/psimi) which requires `org.biopax.paxtools.io.jena.JenaIOHandler`. However commit e63cdcc4f0 removed this library. What is the suggested method to migrate?

**Comment by IgorRodchenkov** [comment]
This issue belongs to the psimi, not here. You need to either keep using the old code and paxtools library there or update paxtools  dependency there and also fix that (psimi module) code to use SimpleIOHandler instead of the JenaIOHandler. But better somehow use the paxtools/psimi-converter module instead of that old psimi-xml-rdf module.

**Comment by IgorRodchenkov** [comment]
So, would you consider removing that old psimi-xml-rdf module from the psimi libs and use a better and more recent converter to BioPAX: https://github.com/BioPAX/Paxtools/tree/master/psimi-converter (instead of trying to upgrade)? But if you're going to upgrade/fix that psimi library, then yes we normally do not have to use Jena library to read/write BioPAX L2/L3. See org.biopax.paxtools.io.SimpleIOHandler, https://www.biopax.org/Paxtools/, there is a PDF guide attached with the paper at https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003194#s6 and also the same (I bet) paxtools.pdf in https://sourceforge.net/projects/biopax/files/paxtools/. The last Paxtools release was 5.1.0, the last snapshot is 5.2.1-SNAPSHOT, and it's been almost three or more years ago...
